'use strict';window.DOMHandler=class{constructor(e,g){this._iRuntime=e;this._componentId=g;this._hasTickCallback=!1;this._tickCallback=()=>this.Tick()}Attach(){}PostToRuntime(e,g,h,m){this._iRuntime.PostToRuntimeComponent(this._componentId,e,g,h,m)}PostToRuntimeAsync(e,g,h,m){return this._iRuntime.PostToRuntimeComponentAsync(this._componentId,e,g,h,m)}_PostToRuntimeMaybeSync(e,g,h){this._iRuntime.UsesWorker()?this.PostToRuntime(e,g,h):this._iRuntime._GetLocalRuntime()._OnMessageFromDOM({type:"event",
component:this._componentId,handler:e,dispatchOpts:h||null,data:g,responseId:null})}AddRuntimeMessageHandler(e,g){this._iRuntime.AddRuntimeComponentMessageHandler(this._componentId,e,g)}AddRuntimeMessageHandlers(e){for(const [g,h]of e)this.AddRuntimeMessageHandler(g,h)}GetRuntimeInterface(){return this._iRuntime}GetComponentID(){return this._componentId}_StartTicking(){this._hasTickCallback||(this._iRuntime._AddRAFCallback(this._tickCallback),this._hasTickCallback=!0)}_StopTicking(){this._hasTickCallback&&
(this._iRuntime._RemoveRAFCallback(this._tickCallback),this._hasTickCallback=!1)}Tick(){}};
window.RateLimiter=class{constructor(e,g){this._callback=e;this._interval=g;this._timerId=-1;this._lastCallTime=-Infinity;this._timerCallFunc=()=>this._OnTimer();this._canRunImmediate=this._ignoreReset=!1}SetCanRunImmediate(e){this._canRunImmediate=!!e}Call(){if(-1===this._timerId){var e=Date.now(),g=e-this._lastCallTime,h=this._interval;g>=h&&this._canRunImmediate?(this._lastCallTime=e,this._RunCallback()):this._timerId=self.setTimeout(this._timerCallFunc,Math.max(h-g,4))}}_RunCallback(){this._ignoreReset=
!0;this._callback();this._ignoreReset=!1}Reset(){this._ignoreReset||(this._CancelTimer(),this._lastCallTime=Date.now())}_OnTimer(){this._timerId=-1;this._lastCallTime=Date.now();this._RunCallback()}_CancelTimer(){-1!==this._timerId&&(self.clearTimeout(this._timerId),this._timerId=-1)}Release(){this._CancelTimer();this._timerCallFunc=this._callback=null}};"use strict";
window.DOMElementHandler=class extends self.DOMHandler{constructor(e,g){super(e,g);this._elementMap=new Map;this._autoAttach=!0;this.AddRuntimeMessageHandlers([["create",h=>this._OnCreate(h)],["destroy",h=>this._OnDestroy(h)],["set-visible",h=>this._OnSetVisible(h)],["update-position",h=>this._OnUpdatePosition(h)],["update-state",h=>this._OnUpdateState(h)],["focus",h=>this._OnSetFocus(h)],["set-css-style",h=>this._OnSetCssStyle(h)],["set-attribute",h=>this._OnSetAttribute(h)],["remove-attribute",
h=>this._OnRemoveAttribute(h)]]);this.AddDOMElementMessageHandler("get-element",h=>h)}SetAutoAttach(e){this._autoAttach=!!e}AddDOMElementMessageHandler(e,g){this.AddRuntimeMessageHandler(e,h=>{const m=this._elementMap.get(h.elementId);return g(m,h)})}_OnCreate(e){const g=e.elementId,h=this.CreateElement(g,e);this._elementMap.set(g,h);e.isVisible||(h.style.display="none");e=this._GetFocusElement(h);e.addEventListener("focus",m=>this._OnFocus(g));e.addEventListener("blur",m=>this._OnBlur(g));this._autoAttach&&
document.body.appendChild(h)}CreateElement(e,g){throw Error("required override");}DestroyElement(e){}_OnDestroy(e){e=e.elementId;const g=this._elementMap.get(e);this.DestroyElement(g);this._autoAttach&&g.parentElement.removeChild(g);this._elementMap.delete(e)}PostToRuntimeElement(e,g,h){h||(h={});h.elementId=g;this.PostToRuntime(e,h)}_PostToRuntimeElementMaybeSync(e,g,h){h||(h={});h.elementId=g;this._PostToRuntimeMaybeSync(e,h)}_OnSetVisible(e){this._autoAttach&&(this._elementMap.get(e.elementId).style.display=
e.isVisible?"":"none")}_OnUpdatePosition(e){if(this._autoAttach){var g=this._elementMap.get(e.elementId);g.style.left=e.left+"px";g.style.top=e.top+"px";g.style.width=e.width+"px";g.style.height=e.height+"px";e=e.fontSize;null!==e&&(g.style.fontSize=e+"em")}}_OnUpdateState(e){const g=this._elementMap.get(e.elementId);this.UpdateState(g,e)}UpdateState(e,g){throw Error("required override");}_GetFocusElement(e){return e}_OnFocus(e){this.PostToRuntimeElement("elem-focused",e)}_OnBlur(e){this.PostToRuntimeElement("elem-blurred",
e)}_OnSetFocus(e){const g=this._GetFocusElement(this._elementMap.get(e.elementId));e.focus?g.focus():g.blur()}_OnSetCssStyle(e){this._elementMap.get(e.elementId).style[e.prop]=e.val}_OnSetAttribute(e){this._elementMap.get(e.elementId).setAttribute(e.name,e.val)}_OnRemoveAttribute(e){this._elementMap.get(e.elementId).removeAttribute(e.name)}GetElementById(e){return this._elementMap.get(e)}};"use strict";
{const e=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let g=0;function h(c,a){const d=document.createElement("script");d.async=!1;"module"===a&&(d.type="module");return c.isStringSrc?new Promise(f=>{const k="c3_resolve_"+g;++g;self[k]=f;d.textContent=c.str+`\n\nself["${k}"]();`;document.head.appendChild(d)}):new Promise((f,k)=>{d.onload=f;d.onerror=k;d.src=c;document.head.appendChild(d)})}let m=!1,n=!1;function E(){if(!m){try{new Worker("blob://",{get type(){n=!0}})}catch(c){}m=
!0}return n}let u=new Audio;const B={"audio/webm; codecs=opus":!!u.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!u.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!u.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!u.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!u.canPlayType("audio/mp4"),"audio/mpeg":!!u.canPlayType("audio/mpeg")};u=null;async function w(c){c=await C(c);return(new TextDecoder("utf-8")).decode(c)}function C(c){return new Promise((a,
d)=>{const f=new FileReader;f.onload=k=>a(k.target.result);f.onerror=k=>d(k);f.readAsArrayBuffer(c)})}const z=[];let v=0;window.RealFile=window.File;const x=[],r=new Map,y=new Map;let A=0;const D=[];self.runOnStartup=function(c){if("function"!==typeof c)throw Error("runOnStartup called without a function");D.push(c)};const F=new Set(["cordova","playable-ad","instant-games"]);function b(c){return F.has(c)}window.RuntimeInterface=class c{constructor(a){this._useWorker=a.useWorker;this._messageChannelPort=
null;this._baseUrl="";this._scriptFolder=a.scriptFolder;this._scriptsType=a.scriptsType;this._workerScriptURLs={};this._localRuntime=this._worker=null;this._domHandlers=[];this._jobScheduler=this._canvas=this._runtimeDomHandler=null;this._rafId=-1;this._rafFunc=()=>this._OnRAFCallback();this._rafCallbacks=[];this._exportType=a.exportType;!this._useWorker||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&("module"!==this._scriptsType||E())||(this._useWorker=!1);b(this._exportType)&&
this._useWorker&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),this._useWorker=!1);this._localFileStrings=this._localFileBlobs=null;"html5"!==this._exportType&&"playable-ad"!==this._exportType||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.AddRuntimeComponentMessageHandler("runtime",
"cordova-fetch-local-file",d=>this._OnCordovaFetchLocalFile(d));this.AddRuntimeComponentMessageHandler("runtime","create-job-worker",d=>this._OnCreateJobWorker(d));"cordova"===this._exportType?document.addEventListener("deviceready",()=>this._Init(a)):this._Init(a)}Release(){this._CancelAnimationFrame();this._messageChannelPort&&(this._messageChannelPort=this._messageChannelPort.onmessage=null);this._worker&&(this._worker.terminate(),this._worker=null);this._localRuntime&&(this._localRuntime.Release(),
this._localRuntime=null);this._canvas&&(this._canvas.parentElement.removeChild(this._canvas),this._canvas=null)}GetCanvas(){return this._canvas}GetBaseURL(){return this._baseUrl}UsesWorker(){return this._useWorker}GetExportType(){return this._exportType}GetScriptFolder(){return this._scriptFolder}IsiOSCordova(){return e&&"cordova"===this._exportType}IsiOSWebView(){return e&&b(this._exportType)||navigator.standalone}async _Init(a){if("playable-ad"===this._exportType){this._localFileBlobs=self.c3_base64files;
this._localFileStrings={};await this._ConvertDataUrisToBlobs();for(let f=0,k=a.engineScripts.length;f<k;++f){var d=a.engineScripts[f].toLowerCase();this._localFileStrings.hasOwnProperty(d)?a.engineScripts[f]={isStringSrc:!0,str:this._localFileStrings[d]}:this._localFileBlobs.hasOwnProperty(d)&&(a.engineScripts[f]=URL.createObjectURL(this._localFileBlobs[d]))}}a.baseUrl?this._baseUrl=a.baseUrl:(d=location.origin,this._baseUrl=("null"===d?"file:///":d)+location.pathname,d=this._baseUrl.lastIndexOf("/"),
-1!==d&&(this._baseUrl=this._baseUrl.substr(0,d+1)));a.workerScripts&&(this._workerScriptURLs=a.workerScripts);d=new MessageChannel;this._messageChannelPort=d.port1;this._messageChannelPort.onmessage=f=>this._OnMessageFromRuntime(f.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(f=>this._OnMessageFromDebugger(f));this._jobScheduler=new self.JobSchedulerDOM(this);await this._jobScheduler.Init();"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&
window.AndroidFullScreen.immersiveMode();this._useWorker?await this._InitWorker(a,d.port2):await this._InitDOM(a,d.port2)}_GetWorkerURL(a){a=this._workerScriptURLs.hasOwnProperty(a)?this._workerScriptURLs[a]:a.endsWith("/workermain.js")&&this._workerScriptURLs.hasOwnProperty("workermain.js")?this._workerScriptURLs["workermain.js"]:"playable-ad"===this._exportType&&this._localFileBlobs.hasOwnProperty(a.toLowerCase())?this._localFileBlobs[a.toLowerCase()]:a;a instanceof Blob&&(a=URL.createObjectURL(a));
return a}async CreateWorker(a,d,f){if(a.startsWith("blob:"))return new Worker(a,f);if(this.IsiOSCordova()&&"file:"===location.protocol)return a=await this.CordovaFetchLocalFileAsArrayBuffer(this._scriptFolder+a),a=new Blob([a],{type:"application/javascript"}),new Worker(URL.createObjectURL(a),f);a=new URL(a,d);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),f)}return new Worker(a,f)}_GetWindowInnerWidth(){return Math.max(window.innerWidth,
1)}_GetWindowInnerHeight(){return Math.max(window.innerHeight,1)}_GetCommonRuntimeOptions(a){return{baseUrl:this._baseUrl,windowInnerWidth:this._GetWindowInnerWidth(),windowInnerHeight:this._GetWindowInnerHeight(),devicePixelRatio:window.devicePixelRatio,isFullscreen:c.IsDocumentFullscreen(),projectData:a.projectData,scriptsType:a.scriptsType,previewImageBlobs:window.cr_previewImageBlobs||this._localFileBlobs,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,
swClientId:window.cr_swClientId||"",exportType:a.exportType,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.ife,jobScheduler:this._jobScheduler.GetPortData(),supportedAudioFormats:B,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this._scriptFolder+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this._scriptFolder+"opus.wasm.wasm",isiOSCordova:this.IsiOSCordova(),isiOSWebView:this.IsiOSWebView(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async _InitWorker(a,
d){var f=this._GetWorkerURL(a.workerMainUrl);this._worker=await this.CreateWorker(f,this._baseUrl,{type:this._scriptsType,name:"Runtime"});this._canvas=document.createElement("canvas");this._canvas.style.display="none";f=this._canvas.transferControlToOffscreen();document.body.appendChild(this._canvas);window.c3canvas=this._canvas;this._worker.postMessage(Object.assign(this._GetCommonRuntimeOptions(a),{type:"init-runtime",isInWorker:!0,messagePort:d,canvas:f,workerDependencyScripts:a.workerDependencyScripts||
[],engineScripts:a.engineScripts,projectScripts:a.projectScripts,mainProjectScript:a.mainProjectScript,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[d,f,...this._jobScheduler.GetPortTransferables()]);this._domHandlers=x.map(k=>new k(this));this._FindRuntimeDOMHandler();self.c3_callFunction=(k,l)=>this._runtimeDomHandler._InvokeFunctionFromJS(k,l);"preview"===this._exportType&&(self.goToLastErrorScript=()=>this.PostToRuntimeComponent("runtime","go-to-last-error-script"))}async _InitDOM(a,d){this._canvas=
document.createElement("canvas");this._canvas.style.display="none";document.body.appendChild(this._canvas);window.c3canvas=this._canvas;this._domHandlers=x.map(l=>new l(this));this._FindRuntimeDOMHandler();var f=a.engineScripts.map(l=>"string"===typeof l?(new URL(l,this._baseUrl)).toString():l);Array.isArray(a.workerDependencyScripts)&&f.unshift(...a.workerDependencyScripts);f=await Promise.all(f.map(l=>this._MaybeGetCordovaScriptURL(l,this._scriptsType)));await Promise.all(f.map(l=>h(l,this._scriptsType)));
const k=self.C3_ProjectScriptsStatus;if("module"===this._scriptsType){f=a.mainProjectScript;const l=a.projectScripts;for(let [q,p]of l)if(p||(p=q),q===f)try{p=await this._MaybeGetCordovaScriptURL(p,this._scriptsType),await h(p,this._scriptsType),"preview"!==this._exportType||k[q]||this._ReportProjectMainScriptError(q,"main script did not run to completion")}catch(t){this._ReportProjectMainScriptError(q,t)}else if("scriptsInEvents.js"===q||q.endsWith("/scriptsInEvents.js"))p=await this._MaybeGetCordovaScriptURL(p,
this._scriptsType),await h(p,this._scriptsType)}else if(a.projectScripts&&0<a.projectScripts.length)try{if(await Promise.all(a.projectScripts.map(l=>h(l[1],this._scriptsType))),Object.values(k).some(l=>!l)){self.setTimeout(()=>this._ReportProjectScriptError(k),100);return}}catch(l){console.error("[Preview] Error loading project scripts: ",l);self.setTimeout(()=>this._ReportProjectScriptError(k),100);return}"preview"===this._exportType&&"object"!==typeof self.C3.ScriptsInEvents?(this._RemoveLoadingMessage(),
console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this._GetCommonRuntimeOptions(a),{isInWorker:!1,messagePort:d,canvas:this._canvas,runOnStartupFunctions:D}),this._OnBeforeCreateRuntime(),this._localRuntime=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this._localRuntime,a))}_ReportProjectScriptError(a){this._RemoveLoadingMessage();
a=`Failed to load project script '${Object.entries(a).filter(d=>!d[1]).map(d=>d[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+a);alert(a)}_ReportProjectMainScriptError(a,d){this._RemoveLoadingMessage();console.error(`[Preview] Failed to load project main script (${a}): `,d);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}_OnBeforeCreateRuntime(){this._RemoveLoadingMessage()}_RemoveLoadingMessage(){const a=
window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async _OnCreateJobWorker(a){a=await this._jobScheduler._CreateJobWorker();return{outputPort:a,transferables:[a]}}_GetLocalRuntime(){if(this._useWorker)throw Error("not available in worker mode");return this._localRuntime}PostToRuntimeComponent(a,d,f,k,l){this._messageChannelPort.postMessage({type:"event",component:a,handler:d,dispatchOpts:k||null,data:f,responseId:null},l)}PostToRuntimeComponentAsync(a,
d,f,k,l){const q=A++,p=new Promise((t,G)=>{y.set(q,{resolve:t,reject:G})});this._messageChannelPort.postMessage({type:"event",component:a,handler:d,dispatchOpts:k||null,data:f,responseId:q},l);return p}["_OnMessageFromRuntime"](a){const d=a.type;if("event"===d)return this._OnEventFromRuntime(a);if("result"===d)this._OnResultFromRuntime(a);else if("runtime-ready"===d)this._OnRuntimeReady();else if("alert-error"===d)this._RemoveLoadingMessage(),alert(a.message);else if("creating-runtime"===d)this._OnBeforeCreateRuntime();
else throw Error(`unknown message '${d}'`);}_OnEventFromRuntime(a){const d=a.component,f=a.handler,k=a.data,l=a.responseId;if(a=r.get(d))if(a=a.get(f)){var q=null;try{q=a(k)}catch(p){console.error(`Exception in '${d}' handler '${f}':`,p);null!==l&&this._PostResultToRuntime(l,!1,""+p);return}if(null===l)return q;q&&q.then?q.then(p=>this._PostResultToRuntime(l,!0,p)).catch(p=>{console.error(`Rejection from '${d}' handler '${f}':`,p);this._PostResultToRuntime(l,!1,""+p)}):this._PostResultToRuntime(l,
!0,q)}else console.warn(`[DOM] No handler '${f}' for component '${d}'`);else console.warn(`[DOM] No event handlers for component '${d}'`)}_PostResultToRuntime(a,d,f){let k;f&&f.transferables&&(k=f.transferables);this._messageChannelPort.postMessage({type:"result",responseId:a,isOk:d,result:f},k)}_OnResultFromRuntime(a){const d=a.responseId,f=a.isOk;a=a.result;const k=y.get(d);f?k.resolve(a):k.reject(a);y.delete(d)}AddRuntimeComponentMessageHandler(a,d,f){let k=r.get(a);k||(k=new Map,r.set(a,k));if(k.has(d))throw Error(`[DOM] Component '${a}' already has handler '${d}'`);
k.set(d,f)}static AddDOMHandlerClass(a){if(x.includes(a))throw Error("DOM handler already added");x.push(a)}_FindRuntimeDOMHandler(){for(const a of this._domHandlers)if("runtime"===a.GetComponentID()){this._runtimeDomHandler=a;return}throw Error("cannot find runtime DOM handler");}_OnMessageFromDebugger(a){this.PostToRuntimeComponent("debugger","message",a)}_OnRuntimeReady(){for(const a of this._domHandlers)a.Attach()}static IsDocumentFullscreen(){return!!(document.fullscreenElement||document.webkitFullscreenElement||
document.mozFullScreenElement)}async GetRemotePreviewStatusInfo(){return await this.PostToRuntimeComponentAsync("runtime","get-remote-preview-status-info")}_AddRAFCallback(a){this._rafCallbacks.push(a);this._RequestAnimationFrame()}_RemoveRAFCallback(a){a=this._rafCallbacks.indexOf(a);if(-1===a)throw Error("invalid callback");this._rafCallbacks.splice(a,1);this._rafCallbacks.length||this._CancelAnimationFrame()}_RequestAnimationFrame(){-1===this._rafId&&this._rafCallbacks.length&&(this._rafId=requestAnimationFrame(this._rafFunc))}_CancelAnimationFrame(){-1!==
this._rafId&&(cancelAnimationFrame(this._rafId),this._rafId=-1)}_OnRAFCallback(){this._rafId=-1;for(const a of this._rafCallbacks)a();this._RequestAnimationFrame()}TryPlayMedia(a){this._runtimeDomHandler.TryPlayMedia(a)}RemovePendingPlay(a){this._runtimeDomHandler.RemovePendingPlay(a)}_PlayPendingMedia(){this._runtimeDomHandler._PlayPendingMedia()}SetSilent(a){this._runtimeDomHandler.SetSilent(a)}IsAudioFormatSupported(a){return!!B[a]}async _WasmDecodeWebMOpus(a){a=await this.PostToRuntimeComponentAsync("runtime",
"opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}IsAbsoluteURL(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}IsRelativeURL(a){return!this.IsAbsoluteURL(a)}async _MaybeGetCordovaScriptURL(a,d){return"cordova"===this._exportType&&"module"===d&&(a.startsWith("file:")||"file:"===location.protocol&&this.IsRelativeURL(a))?(a.startsWith(this._baseUrl)&&(a=a.substr(this._baseUrl.length)),a=await this.CordovaFetchLocalFileAsArrayBuffer(a),a=new Blob([a],
{type:"application/javascript"}),URL.createObjectURL(a)):a}async _OnCordovaFetchLocalFile(a){const d=a.filename;switch(a.as){case "text":return await this.CordovaFetchLocalFileAsText(d);case "buffer":return await this.CordovaFetchLocalFileAsArrayBuffer(d);default:throw Error("unsupported type");}}_GetPermissionAPI(){const a=window.cordova&&window.cordova.plugins&&window.cordova.plugins.permissions;if("object"!==typeof a)throw Error("Permission API is not loaded");return a}_MapPermissionID(a,d){a=
a[d];if("string"!==typeof a)throw Error("Invalid permission name");return a}_HasPermission(a){const d=this._GetPermissionAPI();return new Promise((f,k)=>d.checkPermission(this._MapPermissionID(d,a),l=>f(!!l.hasPermission),k))}_RequestPermission(a){const d=this._GetPermissionAPI();return new Promise((f,k)=>d.requestPermission(this._MapPermissionID(d,a),l=>f(!!l.hasPermission),k))}async RequestPermissions(a){if("cordova"!==this.GetExportType()||this.IsiOSCordova())return!0;for(const d of a)if(!await this._HasPermission(d)&&
!1===await this._RequestPermission(d))return!1;return!0}async RequirePermissions(...a){if(!1===await this.RequestPermissions(a))throw Error("Permission not granted");}CordovaFetchLocalFile(a){const d=window.cordova.file.applicationDirectory+"www/"+a.toLowerCase();return new Promise((f,k)=>{window.resolveLocalFileSystemURL(d,l=>{l.file(f,k)},k)})}async CordovaFetchLocalFileAsText(a){a=await this.CordovaFetchLocalFile(a);return await w(a)}_CordovaMaybeStartNextArrayBufferRead(){if(z.length&&!(8<=v)){v++;
var a=z.shift();this._CordovaDoFetchLocalFileAsAsArrayBuffer(a.filename,a.successCallback,a.errorCallback)}}CordovaFetchLocalFileAsArrayBuffer(a){return new Promise((d,f)=>{z.push({filename:a,successCallback:k=>{v--;this._CordovaMaybeStartNextArrayBufferRead();d(k)},errorCallback:k=>{v--;this._CordovaMaybeStartNextArrayBufferRead();f(k)}});this._CordovaMaybeStartNextArrayBufferRead()})}async _CordovaDoFetchLocalFileAsAsArrayBuffer(a,d,f){try{const k=await this.CordovaFetchLocalFile(a),l=await C(k);
d(l)}catch(k){f(k)}}async _ConvertDataUrisToBlobs(){const a=[];for(const [d,f]of Object.entries(this._localFileBlobs))a.push(this._ConvertDataUriToBlobs(d,f));await Promise.all(a)}async _ConvertDataUriToBlobs(a,d){if("object"===typeof d)this._localFileBlobs[a]=new Blob([d.str],{type:d.type}),this._localFileStrings[a]=d.str;else{let f=await this._FetchDataUri(d);f||(f=this._DataURIToBinaryBlobSync(d));this._localFileBlobs[a]=f}}async _FetchDataUri(a){try{return await (await fetch(a)).blob()}catch(d){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
d),null}}_DataURIToBinaryBlobSync(a){a=this._ParseDataURI(a);return this._BinaryStringToBlob(a.data,a.mime_type)}_ParseDataURI(a){var d=a.indexOf(",");if(0>d)throw new URIError("expected comma in data: uri");var f=a.substring(5,d);a=a.substring(d+1);d=f.split(";");f=d[0]||"";const k=d[2];a="base64"===d[1]||"base64"===k?atob(a):decodeURIComponent(a);return{mime_type:f,data:a}}_BinaryStringToBlob(a,d){var f=a.length;let k=f>>2,l=new Uint8Array(f),q=new Uint32Array(l.buffer,0,k),p,t;for(t=p=0;p<k;++p)q[p]=
a.charCodeAt(t++)|a.charCodeAt(t++)<<8|a.charCodeAt(t++)<<16|a.charCodeAt(t++)<<24;for(f&=3;f--;)l[t]=a.charCodeAt(t),++t;return new Blob([l],{type:d})}}}"use strict";
{const e=self.RuntimeInterface;function g(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const h=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),m={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},n={dispatchUserScriptEvent:!0},E={dispatchRuntimeEvent:!0};function u(b){return new Promise((c,a)=>{const d=document.createElement("link");d.onload=()=>c(d);d.onerror=
f=>a(f);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function B(b){return new Promise((c,a)=>{const d=new Image;d.onload=()=>c(d);d.onerror=f=>a(f);d.src=b})}async function w(b){b=URL.createObjectURL(b);try{return await B(b)}finally{URL.revokeObjectURL(b)}}function C(b){return new Promise((c,a)=>{let d=new FileReader;d.onload=f=>c(f.target.result);d.onerror=f=>a(f);d.readAsText(b)})}async function z(b,c,a){if(!/firefox/i.test(navigator.userAgent))return await w(b);var d=await C(b);d=
(new DOMParser).parseFromString(d,"image/svg+xml");const f=d.documentElement;if(f.hasAttribute("width")&&f.hasAttribute("height")){const k=f.getAttribute("width"),l=f.getAttribute("height");if(!k.includes("%")&&!l.includes("%"))return await w(b)}f.setAttribute("width",c+"px");f.setAttribute("height",a+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await w(b)}function v(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);
return!1}const x=new Set(["canvas","body","html"]);function r(b){const c=b.target.tagName.toLowerCase();x.has(c)&&b.preventDefault()}function y(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}self.C3_GetSvgImageSize=async function(b){b=await w(b);if(0<b.width&&0<b.height)return[b.width,b.height];{b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const c=b.getBoundingClientRect();document.body.removeChild(b);return[c.width,c.height]}};
self.C3_RasterSvgImageBlob=async function(b,c,a,d,f){b=await z(b,c,a);const k=document.createElement("canvas");k.width=d;k.height=f;k.getContext("2d").drawImage(b,0,0,c,a);return k};let A=!1;document.addEventListener("pause",()=>A=!0);document.addEventListener("resume",()=>A=!1);function D(){try{return window.parent&&window.parent.document.hasFocus()}catch(b){return!1}}function F(){const b=document.activeElement;if(!b)return!1;const c=b.tagName.toLowerCase(),a=new Set("email number password search tel text url".split(" "));
return"textarea"===c?!0:"input"===c?a.has(b.type.toLowerCase()||"text"):v(b)}e.AddDOMHandlerClass(class extends self.DOMHandler{constructor(b){super(b,"runtime");this._isFirstSizeUpdate=!0;this._simulatedResizeTimerId=-1;this._targetOrientation="any";this._attachedDeviceMotionEvent=this._attachedDeviceOrientationEvent=!1;this._lastPointerRawUpdateEvent=this._pointerRawUpdateRateLimiter=this._debugHighlightElem=null;b.AddRuntimeComponentMessageHandler("canvas","update-size",d=>this._OnUpdateCanvasSize(d));
b.AddRuntimeComponentMessageHandler("runtime","invoke-download",d=>this._OnInvokeDownload(d));b.AddRuntimeComponentMessageHandler("runtime","raster-svg-image",d=>this._OnRasterSvgImage(d));b.AddRuntimeComponentMessageHandler("runtime","get-svg-image-size",d=>this._OnGetSvgImageSize(d));b.AddRuntimeComponentMessageHandler("runtime","set-target-orientation",d=>this._OnSetTargetOrientation(d));b.AddRuntimeComponentMessageHandler("runtime","register-sw",()=>this._OnRegisterSW());b.AddRuntimeComponentMessageHandler("runtime",
"post-to-debugger",d=>this._OnPostToDebugger(d));b.AddRuntimeComponentMessageHandler("runtime","go-to-script",d=>this._OnPostToDebugger(d));b.AddRuntimeComponentMessageHandler("runtime","before-start-ticking",()=>this._OnBeforeStartTicking());b.AddRuntimeComponentMessageHandler("runtime","debug-highlight",d=>this._OnDebugHighlight(d));b.AddRuntimeComponentMessageHandler("runtime","enable-device-orientation",()=>this._AttachDeviceOrientationEvent());b.AddRuntimeComponentMessageHandler("runtime","enable-device-motion",
()=>this._AttachDeviceMotionEvent());b.AddRuntimeComponentMessageHandler("runtime","add-stylesheet",d=>this._OnAddStylesheet(d));b.AddRuntimeComponentMessageHandler("runtime","alert",d=>this._OnAlert(d));b.AddRuntimeComponentMessageHandler("runtime","hide-cordova-splash",()=>this._OnHideCordovaSplash());const c=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const f=d.target,k=f.tagName.toLowerCase();c.has(k)||v(f)||d.preventDefault()});const a=b.GetCanvas();window.addEventListener("selectstart",
r);window.addEventListener("gesturehold",r);a.addEventListener("selectstart",r);a.addEventListener("gesturehold",r);window.addEventListener("touchstart",r,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",r,{passive:!1}),a.addEventListener("pointerdown",r)):a.addEventListener("touchstart",r);this._mousePointerLastButtons=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",y,{passive:!1});window.addEventListener("wheel",
y,{passive:!1});window.addEventListener("resize",()=>this._OnWindowResize());window.addEventListener("fullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("webkitfullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("mozfullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("fullscreenerror",d=>this._OnFullscreenError(d));window.addEventListener("webkitfullscreenerror",d=>this._OnFullscreenError(d));window.addEventListener("mozfullscreenerror",
d=>this._OnFullscreenError(d));b.IsiOSWebView()&&window.addEventListener("focusout",()=>{F()||(document.scrollingElement.scrollTop=0)});this._mediaPendingPlay=new Set;this._mediaRemovedPendingPlay=new WeakSet;this._isSilent=!1}_OnBeforeStartTicking(){"cordova"===this._iRuntime.GetExportType()?(document.addEventListener("pause",()=>this._OnVisibilityChange(!0)),document.addEventListener("resume",()=>this._OnVisibilityChange(!1))):document.addEventListener("visibilitychange",()=>this._OnVisibilityChange(document.hidden));
return{isSuspended:!(!document.hidden&&!A)}}Attach(){window.addEventListener("focus",()=>this._PostRuntimeEvent("window-focus"));window.addEventListener("blur",()=>{this._PostRuntimeEvent("window-blur",{parentHasFocus:D()});this._mousePointerLastButtons=0});window.addEventListener("keydown",c=>this._OnKeyEvent("keydown",c));window.addEventListener("keyup",c=>this._OnKeyEvent("keyup",c));window.addEventListener("dblclick",c=>this._OnMouseEvent("dblclick",c,m));window.addEventListener("wheel",c=>this._OnMouseWheelEvent("wheel",
c));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",c=>{this._HandlePointerDownFocus(c);this._OnPointerEvent("pointerdown",c)}),this._iRuntime.UsesWorker()&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this._pointerRawUpdateRateLimiter=new self.RateLimiter(()=>this._DoSendPointerRawUpdate(),5),this._pointerRawUpdateRateLimiter.SetCanRunImmediate(!0),window.addEventListener("pointerrawupdate",c=>this._OnPointerRawUpdate(c))):window.addEventListener("pointermove",
c=>this._OnPointerEvent("pointermove",c)),window.addEventListener("pointerup",c=>this._OnPointerEvent("pointerup",c)),window.addEventListener("pointercancel",c=>this._OnPointerEvent("pointercancel",c))):(window.addEventListener("mousedown",c=>{this._HandlePointerDownFocus(c);this._OnMouseEventAsPointer("pointerdown",c)}),window.addEventListener("mousemove",c=>this._OnMouseEventAsPointer("pointermove",c)),window.addEventListener("mouseup",c=>this._OnMouseEventAsPointer("pointerup",c)),window.addEventListener("touchstart",
c=>{this._HandlePointerDownFocus(c);this._OnTouchEvent("pointerdown",c)}),window.addEventListener("touchmove",c=>this._OnTouchEvent("pointermove",c)),window.addEventListener("touchend",c=>this._OnTouchEvent("pointerup",c)),window.addEventListener("touchcancel",c=>this._OnTouchEvent("pointercancel",c)));const b=()=>this._PlayPendingMedia();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);
window.addEventListener("gamepadconnected",b,!0)}_PostRuntimeEvent(b,c){this.PostToRuntime(b,c||null,E)}_GetWindowInnerWidth(){return this._iRuntime._GetWindowInnerWidth()}_GetWindowInnerHeight(){return this._iRuntime._GetWindowInnerHeight()}_OnWindowResize(){const b=this._GetWindowInnerWidth(),c=this._GetWindowInnerHeight();this._PostRuntimeEvent("window-resize",{innerWidth:b,innerHeight:c,devicePixelRatio:window.devicePixelRatio});this._iRuntime.IsiOSWebView()&&(-1!==this._simulatedResizeTimerId&&
clearTimeout(this._simulatedResizeTimerId),this._OnSimulatedResize(b,c,0))}_ScheduleSimulatedResize(b,c,a){-1!==this._simulatedResizeTimerId&&clearTimeout(this._simulatedResizeTimerId);this._simulatedResizeTimerId=setTimeout(()=>this._OnSimulatedResize(b,c,a),48)}_OnSimulatedResize(b,c,a){const d=this._GetWindowInnerWidth(),f=this._GetWindowInnerHeight();this._simulatedResizeTimerId=-1;d!=b||f!=c?this._PostRuntimeEvent("window-resize",{innerWidth:d,innerHeight:f,devicePixelRatio:window.devicePixelRatio}):
10>a&&this._ScheduleSimulatedResize(d,f,a+1)}_OnSetTargetOrientation(b){this._targetOrientation=b.targetOrientation}_TrySetTargetOrientation(){const b=this._targetOrientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(c=>console.warn("[Construct 3] Failed to lock orientation: ",c));else try{let c=!1;screen.lockOrientation?c=screen.lockOrientation(b):screen.webkitLockOrientation?c=screen.webkitLockOrientation(b):screen.mozLockOrientation?c=screen.mozLockOrientation(b):
screen.msLockOrientation&&(c=screen.msLockOrientation(b));c||console.warn("[Construct 3] Failed to lock orientation")}catch(c){console.warn("[Construct 3] Failed to lock orientation: ",c)}}_OnFullscreenChange(){const b=e.IsDocumentFullscreen();b&&"any"!==this._targetOrientation&&this._TrySetTargetOrientation();this.PostToRuntime("fullscreenchange",{isFullscreen:b,innerWidth:this._GetWindowInnerWidth(),innerHeight:this._GetWindowInnerHeight()})}_OnFullscreenError(b){console.warn("[Construct 3] Fullscreen request failed: ",
b);this.PostToRuntime("fullscreenerror",{isFullscreen:e.IsDocumentFullscreen(),innerWidth:this._GetWindowInnerWidth(),innerHeight:this._GetWindowInnerHeight()})}_OnVisibilityChange(b){b?this._iRuntime._CancelAnimationFrame():this._iRuntime._RequestAnimationFrame();this.PostToRuntime("visibilitychange",{hidden:b})}_OnKeyEvent(b,c){"Backspace"===c.key&&r(c);const a=h.get(c.code)||c.code;this._PostToRuntimeMaybeSync(b,{code:a,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,
metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},m)}_OnMouseWheelEvent(b,c){this.PostToRuntime(b,{clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,deltaX:c.deltaX,deltaY:c.deltaY,deltaZ:c.deltaZ,deltaMode:c.deltaMode,timeStamp:c.timeStamp},m)}_OnMouseEvent(b,c,a){g(c)||this._PostToRuntimeMaybeSync(b,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,timeStamp:c.timeStamp},a)}_OnMouseEventAsPointer(b,c){if(!g(c)){var a=this._mousePointerLastButtons;
"pointerdown"===b&&0!==a?b="pointermove":"pointerup"===b&&0!==c.buttons&&(b="pointermove");this._PostToRuntimeMaybeSync(b,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:a,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},m);this._mousePointerLastButtons=c.buttons;this._OnMouseEvent(c.type,c,n)}}_OnPointerEvent(b,c){this._pointerRawUpdateRateLimiter&&"pointermove"!==
b&&this._pointerRawUpdateRateLimiter.Reset();var a=0;"mouse"===c.pointerType&&(a=this._mousePointerLastButtons);this._PostToRuntimeMaybeSync(b,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:a,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},m);"mouse"===c.pointerType&&
(a="mousemove","pointerdown"===b?a="mousedown":"pointerup"===b&&(a="mouseup"),this._OnMouseEvent(a,c,n),this._mousePointerLastButtons=c.buttons)}_OnPointerRawUpdate(b){this._lastPointerRawUpdateEvent=b;this._pointerRawUpdateRateLimiter.Call()}_DoSendPointerRawUpdate(){this._OnPointerEvent("pointermove",this._lastPointerRawUpdateEvent);this._lastPointerRawUpdateEvent=null}_OnTouchEvent(b,c){for(let a=0,d=c.changedTouches.length;a<d;++a){const f=c.changedTouches[a];this._PostToRuntimeMaybeSync(b,{pointerId:f.identifier,
pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY,pageX:f.pageX,pageY:f.pageY,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},m)}}_HandlePointerDownFocus(b){window!==window.top&&window.focus();this._IsElementCanvasOrDocument(b.target)&&document.activeElement&&!this._IsElementCanvasOrDocument(document.activeElement)&&
document.activeElement.blur()}_IsElementCanvasOrDocument(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}_AttachDeviceOrientationEvent(){this._attachedDeviceOrientationEvent||(this._attachedDeviceOrientationEvent=!0,window.addEventListener("deviceorientation",b=>this._OnDeviceOrientation(b)),window.addEventListener("deviceorientationabsolute",b=>this._OnDeviceOrientationAbsolute(b)))}_AttachDeviceMotionEvent(){this._attachedDeviceMotionEvent||(this._attachedDeviceMotionEvent=
!0,window.addEventListener("devicemotion",b=>this._OnDeviceMotion(b)))}_OnDeviceOrientation(b){this.PostToRuntime("deviceorientation",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp,webkitCompassHeading:b.webkitCompassHeading,webkitCompassAccuracy:b.webkitCompassAccuracy},m)}_OnDeviceOrientationAbsolute(b){this.PostToRuntime("deviceorientationabsolute",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp},m)}_OnDeviceMotion(b){let c=
null;var a=b.acceleration;a&&(c={x:a.x||0,y:a.y||0,z:a.z||0});a=null;var d=b.accelerationIncludingGravity;d&&(a={x:d.x||0,y:d.y||0,z:d.z||0});d=null;const f=b.rotationRate;f&&(d={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});this.PostToRuntime("devicemotion",{acceleration:c,accelerationIncludingGravity:a,rotationRate:d,interval:b.interval,timeStamp:b.timeStamp},m)}_OnUpdateCanvasSize(b){const c=this.GetRuntimeInterface().GetCanvas();c.style.width=b.styleWidth+"px";c.style.height=b.styleHeight+
"px";c.style.marginLeft=b.marginLeft+"px";c.style.marginTop=b.marginTop+"px";this._isFirstSizeUpdate&&(c.style.display="",this._isFirstSizeUpdate=!1)}_OnInvokeDownload(b){const c=b.url;b=b.filename;const a=document.createElement("a"),d=document.body;a.textContent=b;a.href=c;a.download=b;d.appendChild(a);a.click();d.removeChild(a)}async _OnRasterSvgImage(b){var c=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);c=c?await createImageBitmap(b,
c):await createImageBitmap(b);return{imageBitmap:c,transferables:[c]}}async _OnGetSvgImageSize(b){return await self.C3_GetSvgImageSize(b.blob)}async _OnAddStylesheet(b){await u(b.url)}_PlayPendingMedia(){var b=[...this._mediaPendingPlay];this._mediaPendingPlay.clear();if(!this._isSilent)for(const c of b)(b=c.play())&&b.catch(a=>{this._mediaRemovedPendingPlay.has(c)||this._mediaPendingPlay.add(c)})}TryPlayMedia(b){if("function"!==typeof b.play)throw Error("missing play function");this._mediaRemovedPendingPlay.delete(b);
let c;try{c=b.play()}catch(a){this._mediaPendingPlay.add(b);return}c&&c.catch(a=>{this._mediaRemovedPendingPlay.has(b)||this._mediaPendingPlay.add(b)})}RemovePendingPlay(b){this._mediaPendingPlay.delete(b);this._mediaRemovedPendingPlay.add(b)}SetSilent(b){this._isSilent=!!b}_OnHideCordovaSplash(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}_OnDebugHighlight(b){if(b.show){this._debugHighlightElem||(this._debugHighlightElem=document.createElement("div"),this._debugHighlightElem.id=
"inspectOutline",document.body.appendChild(this._debugHighlightElem));var c=this._debugHighlightElem;c.style.display="";c.style.left=b.left-1+"px";c.style.top=b.top-1+"px";c.style.width=b.width+2+"px";c.style.height=b.height+2+"px";c.textContent=b.name}else this._debugHighlightElem&&(this._debugHighlightElem.style.display="none")}_OnRegisterSW(){window.C3_RegisterSW&&window.C3_RegisterSW()}_OnPostToDebugger(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}_InvokeFunctionFromJS(b,
c){return this.PostToRuntimeAsync("js-invoke-function",{name:b,params:c})}_OnAlert(b){alert(b.message)}})}"use strict";
self.JobSchedulerDOM=class{constructor(e){this._runtimeInterface=e;this._baseUrl=e.GetBaseURL();"preview"===e.GetExportType()?this._baseUrl+="c3/workers/":this._baseUrl+=e.GetScriptFolder();this._maxNumWorkers=Math.min(navigator.hardwareConcurrency||2,16);this._dispatchWorker=null;this._jobWorkers=[];this._outputPort=this._inputPort=null}async Init(){if(this._hasInitialised)throw Error("already initialised");this._hasInitialised=!0;var e=this._runtimeInterface._GetWorkerURL("dispatchworker.js");this._dispatchWorker=
await this._runtimeInterface.CreateWorker(e,this._baseUrl,{name:"DispatchWorker"});e=new MessageChannel;this._inputPort=e.port1;this._dispatchWorker.postMessage({type:"_init","in-port":e.port2},[e.port2]);this._outputPort=await this._CreateJobWorker()}async _CreateJobWorker(){const e=this._jobWorkers.length;var g=this._runtimeInterface._GetWorkerURL("jobworker.js");g=await this._runtimeInterface.CreateWorker(g,this._baseUrl,{name:"JobWorker"+e});const h=new MessageChannel,m=new MessageChannel;this._dispatchWorker.postMessage({type:"_addJobWorker",
port:h.port1},[h.port1]);g.postMessage({type:"init",number:e,"dispatch-port":h.port2,"output-port":m.port2},[h.port2,m.port2]);this._jobWorkers.push(g);return m.port1}GetPortData(){return{inputPort:this._inputPort,outputPort:this._outputPort,maxNumWorkers:this._maxNumWorkers}}GetPortTransferables(){return[this._inputPort,this._outputPort]}};"use strict";
window.C3_IsSupported&&(window.c3_runtimeInterface=new self.RuntimeInterface({useWorker:!0,workerMainUrl:"workermain.js",engineScripts:["scripts/c3runtime.js"],projectScripts:[],mainProjectScript:"",scriptsType:"module",scriptFolder:"scripts/",workerDependencyScripts:[],exportType:"html5"}));"use strict";
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMHandler{constructor(e){super(e,"touch");this.AddRuntimeMessageHandler("request-permission",g=>this._OnRequestPermission(g))}async _OnRequestPermission(e){e=e.type;let g=!0;0===e?g=await this._RequestOrientationPermission():1===e&&(g=await this._RequestMotionPermission());this.PostToRuntime("permission-result",{type:e,result:g})}async _RequestOrientationPermission(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;
try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(e){return console.warn("[Touch] Failed to request orientation permission: ",e),!1}}async _RequestMotionPermission(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(e){return console.warn("[Touch] Failed to request motion permission: ",e),!1}}});"use strict";
{function e(g){g.stopPropagation()}self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMElementHandler{constructor(g){super(g,"button")}CreateElement(g,h){const m=document.createElement("input");var n=m;h.isCheckbox?(m.type="checkbox",n=document.createElement("label"),n.appendChild(m),n.appendChild(document.createTextNode("")),n.style.fontFamily="sans-serif",n.style.userSelect="none",n.style.webkitUserSelect="none",n.style.display="inline-block",n.style.color="black"):m.type="button";n.style.position=
"absolute";n.addEventListener("touchstart",e);n.addEventListener("touchmove",e);n.addEventListener("touchend",e);n.addEventListener("mousedown",e);n.addEventListener("mouseup",e);n.addEventListener("keydown",e);n.addEventListener("keyup",e);m.addEventListener("click",()=>this._PostToRuntimeElementMaybeSync("click",g,{isChecked:m.checked}));h.id&&(m.id=h.id);this.UpdateState(n,h);return n}_GetInputElem(g){return"input"===g.tagName.toLowerCase()?g:g.firstChild}_GetFocusElement(g){return this._GetInputElem(g)}UpdateState(g,
h){const m=this._GetInputElem(g);m.checked=h.isChecked;m.disabled=!h.isEnabled;g.title=h.title;g===m?m.value=h.text:g.lastChild.textContent=h.text}})};
